version: 2.1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          name: Yarn パッケージキャッシュを復元
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - node/install:
          install-yarn: true
      - run: 
          name: Node のバージョンの確認
          command: node --version
      - run:
          name: 依存関係をインストール
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Yarn パッケージキャッシュを保存
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Lintを実行
          command: yarn lint
      - run:
          name: テストを実行
          command: yarn test --ci --coverage --maxWorkers=2
      - run:
          name: Build
          command: yarn build
orbs:
  node: circleci/node@4.0.0
workflows:
  build_app:
    jobs:
      - build
